# 1. Server Configuration
server.port=${PORT:8080}

# 2. Database Configuration (Sửa lỗi Prepared Statement & Tenant ID)
# Thêm prepareThreshold=0 để tương thích với Supabase Pooler
spring.datasource.url=jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:6543/postgres?options=-c%20search_path%3Dpublic&prepareThreshold=0
spring.datasource.username=postgres.vproubocfxnuyykjboot
spring.datasource.password=N_0907046893
spring.datasource.driver-class-name=org.postgresql.Driver

# 3. Hibernate & JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# 4. MQTT Configuration
# Nếu sếp chưa có Broker trên mạng, dùng tạm Broker công cộng của HiveMQ để test app
mqtt.broker.url=tcp://broker.hivemq.com:1883
mqtt.client.id=smart_workstation_backend

# 5. Security Configuration (JWT)
jwt.secret=SmartWorkstationHCMUT2026SecretKeySecuritySuperLong
jwt.expiration=86400000
