# Để Railway tự động cấp Port
server.port=${PORT:8080}

# Lấy thông tin từ Biến môi trường (Environment Variables)
spring.datasource.url=spring.datasource.url=jdbc:postgresql://[aws-1-ap-southeast-1.pooler.supabase.com:6543/postgres](https://aws-1-ap-southeast-1.pooler.supabase.com:6543/postgres)
spring.datasource.username=postgres
spring.datasource.password=N_0907046893
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

jwt.secret=SmartWorkstationHCMUT2026SecretKeySecuritySuperLong
jwt.expiration=86400000
